name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: [ubuntu-24.04]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: pip install meson ninja
    
    - name: Setup Meson
      run: meson setup build
    
    - name: Compile with Meson
      run: meson compile -C build
    
    - name: Test with Meson
      run: meson test -C build --verbose
